databases:
  - name: apnassl-db
    databaseName: apnassl
    user: apnassl_user

services:
  - type: web
    name: apnassl-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd apnasslproject && gunicorn apnasslproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apnassl-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
